# -*- coding: utf-8 -*-
"""Entrenamiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHRbBDLOHDCzqw7vjSa_69s7zXscH03Z
"""

import torch

# Verificar si la GPU está disponible en PyTorch
print("¿CUDA está disponible?", torch.cuda.is_available())

# Obtener el nombre de la GPU si está disponible
if torch.cuda.is_available():
    print("Nombre de la GPU:", torch.cuda.get_device_name(0))

import os
HOME = os.getcwd()
print(HOME)

#Pip install method (recommended)

!pip install ultralytics
from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="HbpFNNL8Vo8qbYsgKWFk")
project = rf.workspace("latas-u97yx").project("combination-idxrt")
version = project.version(1)
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8m-seg.pt data={dataset.location}/data.yaml epochs=500 imgsz=800 batch=8 workers=8 plots=True

!zip -r train1.zip runs/segment/train

from google.colab import files
files.download('train1.zip')